const SET_DRAWER_ITEM = 'src/store/Constants/SET_DRAWER_ITEM'
const SET_TITLE = 'src/store/Constants/SET_TITLE'
const SET_AMOUNT = 'src/store/Constants/SET_AMOUNT'
const SET_DATE = 'src/store/Constants/SET_DATE'
const SET_TIME = 'src/store/Constants/SET_TIME'
const SET_CATEGORY = 'src/store/Constants/SET_CATEGORY'
const SET_ACCOUNT = 'src/store/Constants/SET_ACCOUNT'
const SET_NOTE = 'src/store/Constants/SET_NOTE'
const SET_TYPE = 'src/store/Constants/SET_TYPE'
const SET_TRANSACTION_DETAILS = 'src/store/Constants/SET_TRANSACTION_DETAILS'
export { SET_TITLE, SET_AMOUNT, SET_DATE, SET_TIME, SET_CATEGORY, SET_ACCOUNT, SET_NOTE, SET_TYPE, SET_DRAWER_ITEM, SET_TRANSACTION_DETAILS }